#!/usr/bin/perl
use strict;
use warnings;
use File::stat;
use Time::localtime;
use Net::OpenSSH;

# Constants
my $VERSION = "1.0.0";
my $HOSTLIST = "$ENV{HOME}/.guesthosts";
my $USERPASS = "";
my $LOCALVERSIONFILE = "$ENV{HOME}/curversion.txt";
my $MOBIUS_BIN = "mobius-hotline-server";
my $LOCALMOBIUS = "$ENV{HOME}/mobius/$MOBIUS_BIN";
my $MOBIUSFOLDER = "$ENV{HOME}/mobius";
my $LOCALDATE = "";
my $MASTER_FILE = "latestmobius.txt";
my $RELEASED_VERSION_FILE = "https://hotline.retro-os.live/$MASTER_FILE";
my $RELEASED_BINARY_FILE = "https://hotline.retro-os.live/$MOBIUS_BIN";
my $WGET_COMMAND = "/usr/bin/wget";
my $MASTERDATE = "";

# Locals

sub GetLocalVersion
{
	open my $INPUT_FILE, "<$LOCALMOBIUS"  || die "Can't open $LOCALMOBIUS: $!\n";

	$LOCALDATE = ctime(stat($INPUT_FILE)->mtime);

	print "Mtime is '$LOCALDATE'\n";
	close ($INPUT_FILE);
}

sub SetLocalVersion
{
	open my $OUTPUT_FILE, ">$LOCALVERSIONFILE"  || die "Can't open $LOCALVERSIONFILE: $!\n";
	print ($OUTPUT_FILE "$LOCALDATE\n");
	close ($OUTPUT_FILE);
}

sub GetMasterVersion
{
	# Download version for the master server
	chdir "/tmp";
	print "Getting master version:\n";
	system ("$WGET_COMMAND $RELEASED_VERSION_FILE > /dev/null 2>\&1");
	open my $INPUT_FILE, "<$MASTER_FILE"  || die "Can't open $MASTER_FILE: $!\n";

        $MASTERDATE = ctime(stat($INPUT_FILE)->mtime);

        print "Mtime is '$LOCALDATE'\n";
        close ($INPUT_FILE);
}

sub DownloadMasterFile
{
	chdir ("/tmp");
	system ("$WGET_COMMAND $RELEASED_BINARY_FILE > /dev/null 2>\&1");
	system ("mv $MOBIUS_BIN $MOBIUSFOLDER"); # ZZZ

print "In download\n";
}

print "check4update v$VERSION\n";
print "====================\n";

GetLocalVersion();

if (! -f $LOCALVERSIONFILE)
{
	print "Local version file ($LOCALVERSIONFILE) does not exist - scanning existing file.\n";
	SetLocalVersion();
}
if ($LOCALDATE eq "")
{
	print "DATE was invalid\n";
	exit (1);
}

print "Checking master mobius:\n";

GetMasterVersion();

if ($LOCALDATE eq $MASTERDATE)
{
	print "Local version up to date\n";
	exit (0);
}

DownloadMasterFile();

exit (0);

# Open the host list
open( my $fh => $HOSTLIST) || die "Cannot open $HOSTLIST: $!";

# Loop for each line
while(my $curline = <$fh>)
{
	chop($curline);
	print "Working on server '$curline'\n";
	my $ssh = Net::OpenSSH->new($curline, user => "hotlineuser", password => $USERPASS);
	$ssh->error and die "Couldn't establish SSH connection: ". $ssh->error;
	$ssh->scp_put("mobius-hotline-server", "/home/hotlineuser/mobius/mobius-hotline-server-update") or die "scp failed: " . $ssh->error;
}
close($fh);

exit (0);

