#!/usr/bin/perl
use strict;
use warnings;
use File::stat;

my $SOURCE_VERSION = "/home/hotlineuser/mobius/mobius-hotline-server";
my $RELEASED_VERSION = "/var/www/html/latestmobius.txt";
my $VERSION = "1.0.0";
my $MD5SUM = "/usr/bin/md5sum -b";

print "markversion v$VERSION - Set the MD5 key for the current version\n";
print "================================================================\n";
if (! -f $SOURCE_VERSION)
{
	print "Source file $SOURCE_VERSION does not exist\n";
	exit (1);
}

#system("$MD5SUM $SOURCE_VERSION > $RELEASED_VERSION")  || die "Can't open $SOURCE_VERSION: $!\n";
system("$MD5SUM $SOURCE_VERSION > $RELEASED_VERSION");

exit (0);
